#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd -P )"
source "${SCRIPT_DIR}/bashLib/commonLib.sh"

docker run                                                                                                             \
    --rm                                                                                                               \
    --name gulp_${RANDOM_SUFFIX}                                                                                       \
    -${TERMINAL_MODE}                                                                                                  \
    -e HOST_USER_ID=${HOST_USER_ID}                                                                                    \
    -e HOST_GROUP_ID=${HOST_GROUP_ID}                                                                                  \
    -v "${HACKY_PREFIX}${SCRIPT_DIR}/../..":/data                                                                      \
    -v "${HACKY_PREFIX}${HOME}/.ssh":/home/developer/.ssh                                                              \
    -v "${HACKY_PREFIX}${HOME}/.gitconfig":/home/developer/.gitconfig                                                  \
    -w "/data/${PRJ_NAME}${REL_DIR}"                                                                                   \
    registry.adsmurai.com:17500/amp/dev/js-tools:latest gulp "$@"                                                      ;
